baseurl = "http://home.jfc.org.uk:8000/bayhorse/"
languageCode = "en-gb"
title = "Buy The Bay Horse"
[params]
    mainIcon = "img/logo.png"

    [[params.social]]
	title = "twitter"
	url = "https://twitter.com/carterjf"

    [[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/jamesfcarter"
