baseurl = "http://thebayhorse.pub/"
languageCode = "en-gb"
title = "Friends of the Bay Horse"
[params]
    mainIcon = "img/logo.png"

    [[params.social]]
	title = "Business Plan"
	icon = "fa-bar-chart-o"
	url = "http://cloud.thebayhorse.pub/s/bezvY3QOEobqyHC"

    [[params.social]]
	title = "Twitter"
	icon = "fa-twitter"
	url = "https://twitter.com/bayhorsefriends"

    [[params.social]]
	title = "Facebook"
	icon = "fa-facebook"
	url = "https://www.facebook.com/friendsofthebayhorse"
