baseurl = "http://home.jfc.org.uk:8000/bayhorse/"
languageCode = "en-gb"
title = "Friends of the Bay Horse"
[params]
    mainIcon = "img/logo.png"

    [[params.social]]
	title = "twitter"
	icon = "twitter"
	url = "https://twitter.com/bayhorsefriends"

    [[params.social]]
	title = "facebook"
	icon = "facebook"
	url = "https://www.facebook.com/friendsofthebayhorse"
